### PR TITLE
Prevent zero divide errors

### LINKED ISSUE #62: ZeroDivisionError
Sorry, another bug report ...

Sequali version was 0.2.0. The command was just `sequali inputfile.fastq`.

The data is Nanopore reads. I cannot share it, but probably you’ll be able to figure out where the problem is from the stacktrace alone:
```
Traceback (most recent call last):
  File ".../.venv/bin/sequali", line 8, in <module>
    sys.exit(main())
  File ".../.venv/lib/python3.10/site-packages/sequali/__main__.py", line 154, in main
    report_modules = calculate_stats(
  File ".../.venv/lib/python3.10/site-packages/sequali/report_modules.py", line 1548, in calculate_stats
    *qc_metrics_modules(metrics, data_ranges),
  File ".../.venv/lib/python3.10/site-packages/sequali/report_modules.py", line 1518, in qc_metrics_modules
    PerPositionMeanQualityAndSpread.from_phred_table_and_labels(
  File ".../.venv/lib/python3.10/site-packages/sequali/report_modules.py", line 441, in from_phred_table_and_labels
    accumulated_errors / accumulated_count))
ZeroDivisionError: float division by zero
```

### PR DESCRIPTION
**Pull request by rhpvorderman**
### Checklist
- [ ] Pull request details were added to CHANGELOG.rst
- [ ] Documentation was updated (if needed)

Should fix  #62 

@marcelm, do you have the possibility to check if this fixes your issue?

`pip install git+https://github.com/rhpvorderman/sequali.git@zerodivide`

### CODE REVIEW

**Comment by marcelm** [comment]
The `ZeroDivisionError` is gone, but now the process doesn’t finish (after three minutes). Hitting Ctrl+C tells me it’s stuck here:
```
`.../report_modules.py", line 441, in from_phred_table_and_labels
    if accumulated_count == 0 or total == accumulated_count:
```
Maybe an infinite loop?

**Comment by rhpvorderman** [comment]
Definitiely infinite loop. It will be hard to debug without the data. The latest commit should be more robust. 

I am really sorry to happily present you a tool that apparently does not survive the first contact with your data. I did test it on real-world data. But alas.

**Comment by rhpvorderman** [comment]
The latest commit does not work? 
What I can also do is place a strategic print statement so that just the count data can be sent to me.

**Comment by marcelm** [comment]
> The latest commit does not work?

No, 3bebc79 still hangs.

I can reproduce it with this single-nucleotid read:
```
@test
A
+
#
```

**Comment by rhpvorderman** [comment]
Thanks I can make a test case out of that.

**Comment by rhpvorderman** [comment]
The hanging should be fixed now. 

It appears pygal's dependency on pkg_resources is causing a crash now. So I will need to fix that too. I will make a separate PR for the emptyness test cases.

**Comment by marcelm** [comment]
I’ve shared the file with you via e-mail. It appears to still hang.

**Comment by rhpvorderman** [comment]
It seems to work. I have send you the report.

**Pull request merged**
